--  AUTHOR: SABARIRAM 
--  DATE: 26/02/2016


--  TO RENAME THE OLD TABELS

RENAME WORD_OBJECT TO V1_WORD_OBJECT;
RENAME PART_OF_SPEECH TO V1_PART_OF_SPEECH;
RENAME PART_OF_SPEECH_CODE TO V1_PART_OF_SPEECH_CODE;
RENAME CONTEXT_MEANING TO V1_CONTEXT_MEANING;
RENAME IDIOM TO V1_IDIOM;
RENAME PHRASAL_VERB TO V1_PHRASAL_VERB;
RENAME ACCENT TO V1_ACCENT;
RENAME PHONOLOGY TO V1_PHONOLLOGY;

ALTER TABLE V1_IDIOM 
DROP CONSTRAINT PK_IDIOM;

ALTER TABLE V1_IDIOM
ADD CONSTRAINT PK_V1_IDIOM PRIMARY KEY (W_ID,P_CODE,I_SEQ);

--  CREATION OF NEW TABLES

-- NOT USED TO CREATE WORD
/*CREATE TABLE WORD(
  WID NUMERIC(4,0) CONSTRAINT PK_WORD PRIMARY KEY
  ,WORD VARCHAR2(50 CHAR) CONSTRAINT NN_WORD__WORD NOT NULL
  ,SYLLABLE VARCHAR2(75 CHAR) CONSTRAINT NN_WORD__SYLLABLE NOT NULL
  ,IFLAG CHAR(1 CHAR) CONSTRAINT NN_WORD__IFLAG NOT NULL
  ,PVFLAG CHAR(1 CHAR) CONSTRAINT NN_WORD__PVFLAG NOT NULL
  ,CONSTRAINT AK_WORD__WORD UNIQUE(WORD)
  ,CONSTRAINT AK_WORD__SYLLABLE UNIQUE(SYLLABLE)
  ,CONSTRAINT CK_WORD__IFLAG CHECK (IFLAG IN('Y','N'))
  ,CONSTRAINT CK_WORD__PVFLAG CHECK (PVFLAG IN('Y','N'))
);

DROP TABLE WORD;*/

CREATE TABLE WORD(
  WID NUMERIC(4,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1
  ,WORD VARCHAR2(50 CHAR) CONSTRAINT NN_WORD__WORD NOT NULL
  ,SYLLABLE VARCHAR2(75 CHAR) CONSTRAINT NN_WORD__SYLLABLE NOT NULL
  ,IFLAG CHAR(1 CHAR) CONSTRAINT NN_WORD__IFLAG NOT NULL
  ,PVFLAG CHAR(1 CHAR) CONSTRAINT NN_WORD__PVFLAG NOT NULL
  ,CONSTRAINT PK_WORD PRIMARY KEY(WID)
  ,CONSTRAINT AK_WORD__WORD UNIQUE(WORD)
  ,CONSTRAINT AK_WORD__SYLLABLE UNIQUE(SYLLABLE)
  ,CONSTRAINT CK_WORD__IFLAG CHECK (IFLAG IN('Y','N'))
  ,CONSTRAINT CK_WORD__PVFLAG CHECK (PVFLAG IN('Y','N'))
);

ALTER TABLE WORD 
ADD CONSTRAINT NN_WORD__WID
CHECK(WID IS NOT NULL);

ALTER TABLE WORD
DROP CONSTRAINT NN_WORD__WID;

ALTER TABLE WORD 
MODIFY WID 
DROP IDENTITY;

ALTER TABLE WORD
RENAME CONSTRAINT SYS_C0010086
TO NN_WORD__WID;

ALTER TABLE WORD 
MODIFY WID 
GENERATED ALWAYS AS IDENTITY 
START WITH 1
INCREMENT BY 1
CACHE 10;

--COMMENT ON TABLE WORD IS 'HOLDS WORD ITSELF AND ITS SYLLABLE, WID IS THE PRIMARY KEY';

CREATE TABLE PS_CODE(
  PCODE NUMBER(2,0)
  ,ABBR VARCHAR2(10 CHAR) CONSTRAINT NN_PS_CODE__ABBR NOT NULL
  ,NAME VARCHAR2(20 CHAR) CONSTRAINT NN_PS_CODE__NAME NOT NULL
  ,PRIMARY KEY(ABBR)
);

ALTER TABLE PS_CODE
MODIFY PRIMARY KEY disable;

ALTER TABLE PS_CODE
DROP PRIMARY KEY;

ALTER TABLE PS_CODE
ADD CONSTRAINT PK_PS_CODE
PRIMARY KEY(PCODE);

ALTER TABLE PS_CODE
ADD CONSTRAINT AK_PS_CODE__ABBR
UNIQUE(ABBR);

ALTER TABLE PS_CODE 
ADD CONSTRAINT AK_PS_CODE__NAME
UNIQUE(NAME);

DROP TABLE PS_CODE;

CREATE TABLE MEANING(
  MID NUMBER(5,0) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1
  ,MEANING VARCHAR2(300 CHAR) CONSTRAINT NN_MEANING__MEANING NOT NULL
  ,CONSTRAINT PK_MEANING PRIMARY KEY(MID)
);

ALTER TABLE MEANING
RENAME CONSTRAINT
SYS_C0010096 TO NN_MEANING__MID;

ALTER TABLE MEANING
MODIFY MID
GENERATED ALWAYS AS IDENTITY 
START WITH 1
INCREMENT BY 1
CACHE 50;

CREATE TABLE EXAMPLE(
  MID NUMBER(5,0)
  ,ESEQ NUMBER(2,0)
  ,EXAMPLE VARCHAR2(300 CHAR) CONSTRAINT NN_EXAMPLE__EXAMPLE NOT NULL
  ,CONSTRAINT PK_EXAMPLE PRIMARY KEY(MID,ESEQ)
);

ALTER TABLE EXAMPLE 
ADD CONSTRAINT FK_EXAMPLE_MEANING
FOREIGN KEY (MID)
REFERENCES MEANING
ON DELETE CASCADE;

ALTER TABLE EXAMPLE
RENAME CONSTRAINT
FK_EXAMPLE_MEANING TO FK_EXAMPLE__MEANING;

CREATE TABLE CTXG_SEQ(
  WID NUMBER(4,0)
  ,CGSEQ NUMBER(2,0)
  ,PCODE NUMBER(2,0) CONSTRAINT NN_PSEQ__PCODE NOT NULL
  ,CONSTRAINT PK_CTXG_SEQ PRIMARY KEY(WID,CGSEQ)
  ,CONSTRAINT FK_CTXG_SEQ__WORD FOREIGN KEY(WID) REFERENCES WORD
  ,CONSTRAINT FK_CTXG_SEQ__PS_CODE FOREIGN KEY(PCODE) REFERENCES PS_CODE 
);

RENAME CTXG_SEQ TO CTX_GRP;

ALTER TABLE CTX_GRP
RENAME CONSTRAINT FK_CTXG_SEQ__WORD TO FK_CTX_GRP__WORD;

ALTER TABLE CTX_GRP
RENAME CONSTRAINT FK_CTXG_SEQ__PS_CODE TO FK_CTX_GRP__PS_CODE;

ALTER TABLE CTX_GRP
RENAME CONSTRAINT PK_CTXG_SEQ TO PK_CTX_GRP;

ALTER TABLE CTX_GRP
DROP CONSTRAINT FK_CTX_GRP__WORD;

ALTER TABLE CTX_GRP
ADD CONSTRAINT FK_CTX_GRP__WORD
FOREIGN KEY(WID) REFERENCES WORD
ON DELETE CASCADE;

ALTER TABLE CTX_GRP
DROP CONSTRAINT FK_CTX_GRP__PS_CODE;

ALTER TABLE CTX_GRP
ADD CONSTRAINT FK_CTX_GRP__PS_CODE
FOREIGN KEY(PCODE) REFERENCES PS_CODE
ON DELETE CASCADE;

ALTER TABLE CTX_GRP
RENAME CONSTRAINT
NN_PSEQ__PCODE TO NN_CTX_GRP__PCODE;

CREATE TABLE CTX_OF_USE(
  WID NUMBER(4,0) CONSTRAINT FK_CTX_OF_USE__WORD REFERENCES WORD ON DELETE CASCADE
  ,PCODE NUMBER(2,0) CONSTRAINT FK_CTX_OF_USE__PS_CODE REFERENCES PS_CODE ON DELETE CASCADE
  ,CSEQ NUMBER(2,0)
  ,CONTEXT VARCHAR2(50 CHAR)
  ,CONSTRAINT PK_CTX_OF_USE PRIMARY KEY(WID,PCODE,CSEQ)
);

DROP TABLE CTX_OF_USE;

DELETE FROM CTX_OF_USE;

ALTER TABLE CTX_OF_USE
DROP CONSTRAINT FK_CTX_OF_USE__PS_CODE;

ALTER TABLE CTX_OF_USE
DROP CONSTRAINT FK_CTX_OF_USE__WORD;

ALTER TABLE CTX_OF_USE
RENAME COLUMN
PCODE TO CGSEQ;

ALTER TABLE CTX_OF_USE
ADD CONSTRAINT FK_CTX_OF_USE__CTX_GRP
FOREIGN KEY(WID,CGSEQ)
REFERENCES CTX_GRP;



CREATE TABLE CTX_MEANG(
  WID NUMBER(4,0)
  ,PCODE NUMBER(2,0)
  ,CSEQ NUMBER(2,0)
  ,MSEQ NUMBER(2,0)
  ,MID NUMBER(5,0) CONSTRAINT NN_CTX_MEANG__MID NOT NULL
  ,CONSTRAINT PK_CTX_MEANG PRIMARY KEY(WID, PCODE, CSEQ, MSEQ)
  ,CONSTRAINT AK_CTX_MEANG__MID UNIQUE(MID)
  ,CONSTRAINT FK_CTX_MEANG__CTX_OF_USE FOREIGN KEY(WID,PCODE,CSEQ) REFERENCES CTX_OF_USE ON DELETE CASCADE
);

ALTER TABLE CTX_MEANG
DROP CONSTRAINT FK_CTX_MEANG__CTX_OF_USE;

ALTER TABLE CTX_MEANG
RENAME COLUMN
PCODE TO CGSEQ;

ALTER TABLE CTX_MEANG
ADD CONSTRAINT FK_CTX_MEANG__CTX_OF_USE
FOREIGN KEY(WID,PCODE,CSEQ) 
REFERENCES CTX_OF_USE 
ON DELETE CASCADE;

ALTER TABLE CTX_MEANG
ADD CONSTRAINT FK_CTX_MEANG_MEANING
FOREIGN KEY(MID)
REFERENCES MEANING
ON DELETE CASCADE;

ALTER TABLE CTX_MEANG
RENAME CONSTRAINT 
FK_CTX_MEANG_MEANING TO FK_CTX_MEANG__MEANING;

CREATE TABLE IDIOM(
  WID NUMBER(4,0)
  ,PCODE NUMBER(2,0)
  ,ISEQ NUMBER(2,0)
  ,FORM VARCHAR2(50 CHAR) CONSTRAINT NN_IDIOM__FORM NOT NULL
);

ALTER TABLE IDIOM
MODIFY FORM VARCHAR2(75 CHAR);

ALTER TABLE IDIOM 
ADD CONSTRAINT PK_IDIOM
PRIMARY KEY(WID,PCODE,ISEQ);

ALTER TABLE IDIOM
ADD CONSTRAINT FK_IDIOM__WORD 
FOREIGN KEY(WID) REFERENCES WORD
ON DELETE CASCADE;

ALTER TABLE IDIOM
ADD CONSTRAINT FK_IDIOM__PS_CODE 
FOREIGN KEY(PCODE) REFERENCES PS_CODE
ON DELETE CASCADE;

ALTER TABLE IDIOM
ADD CONSTRAINT AK_IDIOM__FORM
UNIQUE(FORM);

CREATE TABLE IDM_MEANG(
  WID NUMERIC(4,0)
  ,PCODE NUMERIC(2,0)
  ,ISEQ NUMERIC(2,0)
  ,MSEQ NUMERIC(2,0)
  ,MID NUMERIC(5,0) CONSTRAINT NN_IDM_MEANG__MID NOT NULL
);

DROP TABLE IDM_MEANG;

ALTER TABLE IDM_MEANG
ADD CONSTRAINT PK_IDM_MEANG
PRIMARY KEY(WID,PCODE,ISEQ,MSEQ);

ALTER TABLE IDM_MEANG
ADD CONSTRAINT AK_IDM_MEANG__MID
UNIQUE( MID);

ALTER TABLE IDM_MEANG
ADD CONSTRAINT FK_IDM_MEANG__IDIOM 
FOREIGN KEY(WID,PCODE,ISEQ)
REFERENCES IDIOM
ON DELETE CASCADE;

ALTER TABLE IDM_MEANG
ADD CONSTRAINT FK_IDM_MEANG__MEANING
FOREIGN KEY(MID)
REFERENCES MEANING
ON DELETE CASCADE;

CREATE TABLE P_VERB(
  WID NUMERIC(4,0)
  ,PVSEQ NUMERIC(2,0)
  ,FORM VARCHAR2(50 CHAR) CONSTRAINT NN_P_VERB__FORM NOT NULL
);

ALTER TABLE P_VERB
ADD CONSTRAINT PK_P_VERB
PRIMARY KEY(WID,PVSEQ);

ALTER TABLE P_VERB
ADD CONSTRAINT AK_P_VERB__FORM
UNIQUE(FORM);

ALTER TABLE P_VERB
ADD CONSTRAINT FK_P_VERB__WORD
FOREIGN KEY(WID)
REFERENCES WORD
ON DELETE CASCADE;

CREATE TABLE PV_MEANG(
  WID NUMERIC(4,0)
  ,PVSEQ NUMERIC(2,0)
  ,MSEQ NUMERIC(2,0)
  ,MID NUMBER(5,0) CONSTRAINT NN_PV_MEANG__MID NOT NULL
);


DROP TABLE PV_MEANG;


ALTER TABLE PV_MEANG
ADD CONSTRAINT PK_PV_MEANG
PRIMARY KEY(WID,PVSEQ,MSEQ);

ALTER TABLE PV_MEANG
ADD CONSTRAINT AK_PV_MEANG__MID
UNIQUE(MID);

ALTER TABLE PV_MEANG
ADD CONSTRAINT FK_PV_MEANG__P_VERB
FOREIGN KEY(WID,PVSEQ)
REFERENCES P_VERB
ON DELETE CASCADE;

ALTER TABLE PV_MEANG
DROP CONSTRAINT
FK_PV_MEANG__P_VERB;

ALTER TABLE PV_MEANG
ADD CONSTRAINT FK_PV_MEANG__MEANING
FOREIGN KEY(MID)
REFERENCES MEANING
ON DELETE CASCADE;



DROP TABLE EXAMPLE;
DROP TABLE PV_MEANG;
DROP TABLE IDM_MEANG;
DROP TABLE CTX_MEANG;
DROP TABLE MEANING;
DROP TABLE CTX_OF_USE;
DROP TABLE IDIOM;
DROP TABLE P_VERB;
DROP TABLE WORD;


DELETE FROM CTX_OF_USE;



